# Template Containerfile for building new images

# Enter base image name here - Replace ublue-os if base image is from a different user
FROM ghcr.io/ublue-os/base-main

### MODIFICATIONS
## Make the desired modifications to create a 'tweaked base image' 
#As this repo is meant for creating 'base' images for projects, try to keep things minimal and similar to others

# Copy files from directories
# EXAMPLE - copies update-aurora.sh from the scripts directory and places it into the /tmp directory to be referenced later
COPY scripts/update-cosmic.sh /tmp/update.sh

#Build Container image 
RUN mkdir -p /var/lib/alternatives && \
    /tmp/update.sh && \
    rpm-ostree override replace --experimental --from repo=copr:copr.fedorainfracloud.org:sentry:kernel-blue kernel kernel-headers && \
    ostree container commit
    
